import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers'
import Navbar from './Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IPVerse Frontend Challenge',
  description: 'Generated by create next app',
  link: {
    rel: 'stylesheet',
    href: 'https://fonts.googleapis.com/icon?family=Material+Icons+Round',
  },
}

export default function Layout(props) {
  return (
    <html>
      <head>
        <link rel={metadata.link.rel} href={metadata.link.href} />
        <link rel={metadata.link.rel} href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" />
      </head>
      <body className={[inter.className]}>
        <Providers>
          <Navbar />
          {props.children}
          {props.modal}
        </Providers>
      </body>
    </html>
  )
}
